<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

 商品推荐

In [9]:
# load the dataset
import numpy as np
dsName = "affinity_dataset.txt"
ds = np.loadtxt(dsName)
# 展示前五行
print(ds[:5])


[[0. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]
 [1. 0. 1. 1. 0.]
 [0. 0. 1. 1. 1.]
 [0. 1. 0. 0. 1.]]


支持度：规则的应验程度，在全体里面，给定规则应验的次数
置信度：规则的准确性，满足if条件的里面的规则应验的程度  

In [30]:
from collections import defaultdict
valid_rules = defaultdict(int)
invalid_rules = defaultdict(int)
num_occur = defaultdict(int)
for item in ds:
    for i in range(4):
        if item[i] != 0:
            num_occur[i] += 1
    if item[-1] == 1:
        for k,v in enumerate(item[:-1]):
            if v == 1:
                valid_rules[(k,len(item)-1)] += 1
            else:
                invalid_rules[(k,len(item)-1)] += 1
support = valid_rules
confidence = defaultdict(float)
for rule in valid_rules.keys():
    confidence[rule] = valid_rules[rule] / num_occur[rule[0]]
from operator import itemgetter
sorted_support = sorted(support.items(), key=itemgetter(1), reverse=True)
sorted_confidence = sorted(confidence.items(), key=lambda x:x[1], reverse=True)
for i in range(4):
    print(sorted_support[i],confidence[sorted_support[i][0]])

((2, 5), 27) 0.6585365853658537
((3, 5), 21) 0.5833333333333334
((1, 5), 19) 0.41304347826086957
((0, 5), 17) 0.6296296296296297


反思：  
 - 构建feature map，方便表明feature与index之间的关系  
 - 支持度是数量，置信度是比例：规则（条件加结论）成立 / 条件成立  
 - dict.items()返回字典（k，v）构成的列表
 - sorted reverse是降序排列
